# -*- coding: utf-8 -*-
"""Password-Manager

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-12AfmBPRV9u_2HJAT77WwoJOkb5hyGX
"""

passwords = {}


while True:
  print("\n1. Add a new password")
  print("2. View a password")
  print("3. Exit")


  choice = input("Enter your choice:")

  if choice == "1":
    website = input("Website: ")
    password = input("Password: ")
    passwords[website] = password

  elif choice == "2":
    website = input("Website: ")
    print(passwords.get(website, "Not found"))

  elif choice == "3":
    break